language: cpp

compiler:
- gcc

os:
- linux

dist: bionic

before_install:
- pip install --user cpp-coveralls

env:
  global:
  - MAKEFLAGS="-j 2"

script:
- cmake CMakeLists.txt
- make
- ./URLParser_example

after_success:
- coveralls --exclude CMakeFiles --gcov-options '\-lp'
