language: cpp
compiler:
- gcc
before_install:
- pip install --user cpp-coveralls
os:
- linux
script:
- g++ example/example.cpp -std=c++11 -o urlparser_example
- ./urlparser_example
after_success:
- coveralls --exclude lib --exclude tests --gcov-options '\-lp'
